// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBuEuiopfYTLq-wXN4LPJSEmDgx6q8Bhxg',
    appId: '1:1064590856818:web:923426c329f09aa20168eb',
    messagingSenderId: '1064590856818',
    projectId: 'loginwithotp-f121f',
    authDomain: 'loginwithotp-f121f.firebaseapp.com',
    storageBucket: 'loginwithotp-f121f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAylm-c6z-Fl_zKYaMmXct-b3L6cnKZEFQ',
    appId: '1:1064590856818:android:0a274459447d7c450168eb',
    messagingSenderId: '1064590856818',
    projectId: 'loginwithotp-f121f',
    storageBucket: 'loginwithotp-f121f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_giw7I9yHdse6Z7_3JtZqMD3NXWXYaDk',
    appId: '1:1064590856818:ios:3aaf01222975aeeb0168eb',
    messagingSenderId: '1064590856818',
    projectId: 'loginwithotp-f121f',
    storageBucket: 'loginwithotp-f121f.appspot.com',
    iosBundleId: 'com.kaushal.compleatOneProject',
  );
}
